# Generated by Django 5.0.2 on 2024-03-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_id_alter_product_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Ученик'), ('CREATOR', 'Преподаватель')], max_length=7),
        ),
    ]
