# Generated by Django 5.0.2 on 2024-03-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_userprofile_role_enrollmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_groups',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
